// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Q6LV6tJVABQSQSh6J3GUfQAiOnTD5O8',
    appId: '1:1042862095331:web:c49805fe8271ffd8403ed6',
    messagingSenderId: '1042862095331',
    projectId: 'test-9848c',
    authDomain: 'test-9848c.firebaseapp.com',
    storageBucket: 'test-9848c.appspot.com',
    measurementId: 'G-0H0ETNJFRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRm3Rd6sRrRitVs0sknR0CGklCuVVtwRE',
    appId: '1:1042862095331:android:c4419d712179d0a2403ed6',
    messagingSenderId: '1042862095331',
    projectId: 'test-9848c',
    storageBucket: 'test-9848c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiLv8kjTPDUvk84Beii_Cd1KGOE1pOZ50',
    appId: '1:1042862095331:ios:24b2e66acaa02664403ed6',
    messagingSenderId: '1042862095331',
    projectId: 'test-9848c',
    storageBucket: 'test-9848c.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiLv8kjTPDUvk84Beii_Cd1KGOE1pOZ50',
    appId: '1:1042862095331:ios:95eea72d7c455d16403ed6',
    messagingSenderId: '1042862095331',
    projectId: 'test-9848c',
    storageBucket: 'test-9848c.appspot.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
